# Generated by Django 4.2.20 on 2025-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.TextField(choices=[('CS', 'ComputerScience'), ('ME', 'MechanicalEng'), ('EE', 'Electrical Eng')])),
                ('student_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(choices=[('India', 'IN'), ('America', 'USA')], max_length=20),
        ),
    ]
