# Generated by Django 4.2.20 on 2025-06-28 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libray_app', '0002_students_alter_author_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('penality', models.BooleanField(default=False)),
                ('books_borrowed', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='libray_app.books')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libray_app.students')),
            ],
        ),
    ]
