# Generated by Django 4.2.20 on 2025-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray_app', '0003_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
