# Generated by Django 4.2.20 on 2025-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray_app', '0004_remove_books_is_borrowed_books_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
