# Generated by Django 4.2.20 on 2025-06-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libray_app', '0005_books_is_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='overdue_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
